"""
Plot power-flow timing comparison (PandaPower vs Tensor PF) from pf_compare.json.

Input:
- reproduce/outputs/metrics/pf_compare.json (generated by compare_powerflow.py)

Output:
- reproduce/outputs/figures/pf_compare.png
"""

from __future__ import annotations

import json
from pathlib import Path

import matplotlib.pyplot as plt

ROOT = Path(__file__).resolve().parents[2]
METRIC_PATH = ROOT / "reproduce" / "outputs" / "metrics" / "pf_compare.json"
FIG_DIR = ROOT / "reproduce" / "outputs" / "figures"


def main():
    if not METRIC_PATH.exists():
        print(f"Metric file not found: {METRIC_PATH}")
        return
    with open(METRIC_PATH, "r") as f:
        data = json.load(f)

    labels = []
    values = []
    if data.get("pandapower_per_run_ms") is not None:
        labels.append("PandaPower per run (ms)")
        values.append(data["pandapower_per_run_ms"])
    if data.get("tensor_per_run_ms") is not None:
        labels.append("Tensor PF per run (ms)")
        values.append(data["tensor_per_run_ms"])

    FIG_DIR.mkdir(parents=True, exist_ok=True)
    plt.figure(figsize=(6, 4))
    plt.bar(labels, values, color=["tab:blue", "tab:orange"])
    plt.ylabel("Time (ms)")
    plt.title("Power-flow timing comparison")
    for i, v in enumerate(values):
        plt.text(i, v, f"{v:.2f}", ha="center", va="bottom")
    out = FIG_DIR / "pf_compare.png"
    plt.tight_layout()
    plt.savefig(out, dpi=200)
    plt.close()
    print(f"Saved {out}")


if __name__ == "__main__":
    main()

